### ISSUE TITLE
Button pressed property has no effect

### ISSUE THREAD

**Issue by raymondboswel** [trimble-oss/modus-wc-2.0#720]
### Prerequisites

- [x] I have [searched](https://github.com/trimble-oss/modus-wc-2.0/issues?q=is%3Aissue) for duplicate or closed issues
- [x] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-wc-2.0/blob/main/CONTRIBUTING.md)

### Describe the issue

This can easily be verified with the storybook instance. Toggling `pressed` on/off doesn't do anything. 

### What is the issue regarding?

@trimble-oss/modus-wc

### Priority

Medium

### What product/project are you using Modus Web Components for?

Civil Site Viz

### What is your team/division name?

Field Systems

### Are you willing to contribute?

None

### Are you using Modus Web Components in production?

worksmanager.com

**Comment by prashanthr6383** [comment]
@Sunder005 This issue seems to be alredy fixed by a previos issue #688. Shall we close this

**Comment by karolis-kniuksta-trimble** [comment]
Still doesn't seem to work with package:
"@trimble-oss/moduswebcomponents": "1.0.3",

**Comment by Sunder005** [comment]
Pressed state is not working for any of the variants in the classic theme. This has to be worked upon.
